
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("$plural$/new", "Create $plural$")) ?>
</div>

<?php echo $this->tag->form(array("$plural$/search", "autocomplete" => "off", 'class' => "form-signin")) ?>

<div align="center">
    <h1>Search $plural$</h1>
</div>

<table>
$captureFields$
	<tr>
		<td></td>
		<td><?php echo $this->tag->submitButton(array("Search", "class" => "btn btn-default")) ?></td>
	</tr>
</table>

</form>
