
<?php echo $this->getContent() ?>

<ol class="breadcrumb">
    <li><?php echo $this->tag->linkTo('customers/create', 'Create new customer'); ?></li>
</ol>


<table class="table">
    <?php foreach($customers as $customer) { ?>
        <tr>
            <td><?php echo $this->tag->linkTo('projects/index/'.$customer->getId(), $customer->getName()); ?></td>
            <td><?php echo $customer->Projects->count();?> Projects</td>
        </tr>
    <?php } ?>
</table>