<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("customers/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("customers/new", "Create ")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>User</th>
            <th>Name</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $customer) { ?>
        <tr>
            <td><?php echo $customer->getId() ?></td>
            <td><?php echo $customer->getUserId() ?></td>
            <td><?php echo $customer->getName() ?></td>
            <td><?php echo $this->tag->linkTo(array("customers/edit/" . $customer->getId(), "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("customers/delete/" . $customer->getId(), "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("customers/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("customers/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("customers/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("customers/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>
