
<?php echo $this->getContent() ?>

<ol class="breadcrumb">
    <li><?php echo $this->tag->linkTo('projects/create', 'Create new project'); ?></li>
</ol>

<table class="table">
<?php foreach($output as $o) { ?>
    <tr>
        <td><?php echo $this->tag->linkTo('times/listify/'.$o['id'], $o['name']); ?></td>
        <td><?php echo $o['total'];?>h</td>
        <td><?php echo $o['customer'];?></td>
    </tr>
<?php } ?>
</table>
