
<?php echo $this->tag->form("times/create") ?>

<?php echo $this->getContent(); ?>

<div class="row">
    <div class="form-group col-sm-6">
        <?php echo $this->view->form->label('start'); ?>
        <?php echo $this->view->form->render('start'); ?>
    </div>

    <div class="form-group col-sm-6">
        <?php echo $this->view->form->label('starttime'); ?>
        <?php echo $this->view->form->render('starttime'); ?>
    </div>
</div>
<div class="row">
    <div class="form-group col-sm-6">
        <?php echo $this->view->form->label('end'); ?>
        <?php echo $this->view->form->render('end'); ?>
    </div>
    <div class="form-group col-sm-6">
        <?php echo $this->view->form->label('endtime'); ?>
        <?php echo $this->view->form->render('endtime'); ?>
    </div>
</div>
<div class="form-group">
    <?php echo $this->view->form->label('tempnote'); ?>
    <?php echo $this->view->form->render('tempnote'); ?>
</div>
<div class="form-group">
    <?php echo $this->view->form->label('project_id'); ?>
    <?php echo $this->view->form->render('project_id'); ?>
</div>
<div class="form-group">
    <?php echo $this->view->form->label('location1'); ?>
    <?php echo $this->view->form->render('location1'); ?>
    <?php echo $this->view->form->render('location2'); ?>
</div>
<div class="form-group">
    <?php echo $this->view->form->render('Add'); ?>
    <?php echo $this->view->form->render('csrf'); ?>
</div>


</form>

<script type="text/javascript">

    function getCoords(str) {
        if(str.length > 1) {
            var selector = document.getElementById('location2');

            var req = new XMLHttpRequest();
            req.onreadystatechange  = function(){
                if (req.readyState == 4  )
                {
                    var array = JSON.parse(req.responseText);

                    selector.options.length = 0;
                    for (var i=0; i<array.length; i++){
                        selector.options[i]=new Option(array[i][0], array[i][1] + " " + array[i][2], false, false);
                    }


                }
            };
            req.open("GET", "getGoogleCoords/"+str, true);
            req.send();
        }

    }
</script>