
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("times/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("times", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit times</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="start">Start</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("start", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="end">End</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("end", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="user_id">User</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("user_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="tempnote">Tempnote</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("tempnote", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="project_id">Project</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("project_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
