
<?php echo $this->getContent() ?>

<?php
if($state == 'running') {

echo $this->tag->form();
echo $this->tag->hiddenField(array('action', 'value' => 'stop')); ?>
<div class="input-group">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Stop</button>
                </span>
    <input class="form-control" placeholder="Started <?php echo $halftime->getStart();?>"></input>

</div><br />
</form>
<?php } ?>

<?php echo $this->tag->form();?>
<?php echo $this->tag->hiddenField(array('action', 'value' => 'start')); ?>
<div class="input-group">
        <span class="input-group-btn">
            <button class="btn btn-default" type="submit">Start</button>
        </span>
    <?php echo $this->tag->textField(array('tempnote', 'class' => 'form-control'));?>
</div>
</form>

<h3>Recent</h3>
<div class="btn-group-vertical">
    <?php foreach($recents as $rec) { ?>
        <?php echo $this->tag->form();?>
        <?php echo $this->tag->hiddenField(array('action', 'value' => 'start')); ?>
        <?php echo $this->tag->hiddenField(array('tempnote', 'value' => $rec->tempnote)); ?>
        <button class="btn btn-default" type="submit"><?php echo $rec->tempnote;?></button>
        </form>
    <?php } ?>
</div>

<div align="right">
    <?php echo $this->tag->linkTo(array("times/new", "Create times")) ?>
</div>

<?php echo $this->tag->form(array("times/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search times</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="start">Start</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("start", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="end">End</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("end", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="user_id">User</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("user_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="tempnote">Tempnote</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("tempnote", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="project_id">Project</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("project_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
