
<?php echo $this->getContent() ?>

<?php
if($state == 'running') {

echo $this->tag->form();
echo $this->tag->hiddenField(array('action', 'value' => 'stop')); ?>
<div class="input-group">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Stop</button>
                </span>
    <input class="form-control" placeholder="Started <?php echo $halftime->getStart();?>"></input>

</div><br />
</form>
<?php } ?>

<?php echo $this->tag->form();?>
<?php echo $this->tag->hiddenField(array('action', 'value' => 'start')); ?>
<div class="input-group">
        <span class="input-group-btn">
            <button class="btn btn-default" type="submit">Start</button>
        </span>
    <?php echo $this->tag->textField(array('tempnote', 'class' => 'form-control'));?>
</div>
</form>

<h3>Recent</h3>
<div class="btn-group-vertical">
    <?php foreach($recents as $rec) { ?>
        <?php echo $this->tag->form();?>
        <?php echo $this->tag->hiddenField(array('action', 'value' => 'start')); ?>
        <?php echo $this->tag->hiddenField(array('tempnote', 'value' => $rec->tempnote)); ?>
        <button class="btn btn-default" type="submit"><?php echo $rec->tempnote;?></button>
        </form>
    <?php } ?>
</div>