<?php use Phalcon\Tag;

echo $this->getContent();
$lasttime = 0;
foreach ($page->items as $week => $days) { ?>
<div class="panel panel-primary">

    <div class="panel-heading"><?php echo $week; ?></div>


    <table class="table">
        <thead>
        <tr>
            <th>Date</th>
            <th>Start</th>
            <th>End</th>
            <th>Duration</th>
            <th>Note</th>
            <th>Project</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach($days as $day => $times) {
        for ($i = 0; $i < count($times); $i++) {
            $time = $times[$i];
            $start = strtotime($time->getStart());
            $end = strtotime($time->getStart());

            if(date('z', $start) % 2 == 1)
                $colour = '#f5f5f5';
            else
                $colour = '#ffffff';
            /*
            $diff = $start-$lasttime;
            if($diff > 60 && $diff < 3600*8)
                echo "<tr style='background-color: $colour;'><td colspan='8'><strong>".round($diff/3600, 1)."h gap</strong></td></tr>";

            $lasttime = $end; */
            ?>
            <tr style="background-color: <?php echo $colour ?>;">
                <?php if($i==0) echo "<td style='vertical-align: middle;' rowspan='".count($times)."'>".substr($time->getStart(), 0, 10)."</td>"; ?>
                <td style="vertical-align: "><?php echo substr($time->getStart(), 11, 5) ?></td>
                <td><?php
                    if($time->getEnd() == "0000-00-00 00:00:00")
                        echo "Running";
                    else
                        echo substr($time->getEnd(), 11, 5)
                    ?>
                </td>
                <td><?php echo round($time->getDuration()/3600, 1) ;?>h</td>
                <td><?php echo $time->getTempnote() ?></td>
                <td><?php echo $this->tag->linkTo('times/listify/'.$time->getProjectId(), Helpers::shortify($time->Projects->getName())); ?></td>
                <td class="hidden-print"><?php echo $this->tag->linkTo(array("times/edit/" . $time->getId(), "Edit")); ?></td>
                <td class="hidden-print"><?php echo $this->tag->linkTo(array("times/delete/" . $time->getId(), "Delete")); ?></td>
            </tr>
        <?php } } ?>
        </tbody>
    </table>
</div>
<?php } ?>

<nav>
    <ul class="pagination">
        <li<?php if($page->current == 1) echo ' class="disabled"'; ?>>
            <?php echo $this->tag->linkTo(array("times/listify?page=" . $page->before, "<span aria-hidden=\"true\">&laquo;</span>", 'aria-label' => 'Previous')); ?>
        </li>

        <?php for($i=1;$i<=$page->total_pages;$i++) {?>
        <li<?php if($i == $page->current) echo ' class="active"'; ?>>
            <?php echo $this->tag->linkTo(array("times/listify?page=" . $i, $i)); ?>
        </li>
        <?php } ?>

        <li<?php if($page->current == $page->total_pages) echo ' class="disabled"'; ?>>
            <?php echo $this->tag->linkTo(array("times/listify?page=" . $page->next, "<span aria-hidden=\"true\">&raquo;</span>", 'aria-label' => 'Next')); ?>
        </li>

    </ul>
</nav>