<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->tag->getTitle(); ?>

    <!-- Bootstrap -->
    <?php echo $this->tag->stylesheetLink("css/bootstrap.min.css"); ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://cdn.jsdelivr.net/html5shiv/3.7.1/html5shiv.min.js"></script>
    <script src="https://cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        body {
            padding-top: 70px;
            padding-bottom: 30px;
        }

        @media print {
            a[href]:after {
                content: none;
            }
        }
    </style>
</head>
<body>

<?php echo $this->getContent() ?>

<?php
$profiler = $this->getDI()->get('profiler');
$profiles = $profiler->getProfiles();
$noQueries = $profiler->getNumberTotalStatements();
if($profiles != null) {
?>
<div class="container hidden-print">
    <div class="panel panel-default">
        <ul class="list-group">
        <?php
        foreach ($profiles as $profile)
        {
            if($noQueries > 20 && $profile->getTotalElapsedSeconds() < 0.02) continue;
            ?>
            <li class="list-group-item">
                <?php echo $profile->getSQLStatement(); ?>
                <span class="badge"><?php echo round($profile->getTotalElapsedSeconds(), 3); ?></span>
            </li>
        <?php } ?>
            <li class="list-group-item">Total: <?php echo "$noQueries queries in " . $profiler->getTotalElapsedSeconds(); ?></li>
        </ul>
    </div>
</div>
<?php } ?>
<script>



</script>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<?php echo $this->tag->javascriptInclude("js/bootstrap.min.js"); ?>
</body>
</html>
